apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: uiratan/gitopsfc
  newTag: 8b62f600e403f765334750a86ae05110ab7eea97
